// src/constants/zodiacQuestions.ts

export type QuestionCategory = 'Traços de Personalidade' | 'Estilo de Vida' | 'Gostos e Preferências';

export interface ZodiacQuestion {
  id: number; // 1 a 20
  text: string;
  category: QuestionCategory;
}

// Helper para criar as perguntas facilmente
const q = (id: number, text: string): ZodiacQuestion => {
  let category: QuestionCategory = 'Traços de Personalidade';
  if (id >= 11 && id <= 15) category = 'Estilo de Vida';
  if (id >= 16) category = 'Gostos e Preferências';
  return { id, text, category };
};

// Chaves em Inglês para facilitar o match com o Backend (swisseph)
export const ZODIAC_QUESTIONS: Record<string, ZodiacQuestion[]> = {
  
  // ♑ CAPRICÓRNIO
  Capricorn: [
    q(1, "Tenho metas de vida muito claras, especialmente na carreira, e trabalho com disciplina e persistência."),
    q(2, "A segurança financeira e o conforto material são prioridades fundamentais na minha vida."),
    q(3, "Costumo ser visto(a) como uma pessoa séria e responsável, assumindo deveres com dedicação."),
    q(4, "Minha comunicação é direta, objetiva e prática. Não gosto de rodeios."),
    q(5, "Sinto-me desconfortável em expressar sentimentos abertamente; prefiro demonstrar com ações."),
    q(6, "Sou persistente; encaro obstáculos como desafios e raramente desisto."),
    q(7, "Tenho tendência a ser exigente e crítico(a), tanto comigo quanto com os outros."),
    q(8, "Tenho poucas amizades, mas as que escolho são leais, duradouras e protetoras."),
    q(9, "Gosto de ter tudo planejado e me sinto desconfortável com surpresas de última hora."),
    q(10, "Sou realista, mas preciso cuidar para que meu realismo não vire pessimismo."),
    q(11, "Prefiro investir em poucas peças de alta qualidade e durabilidade do que em muitas baratas."),
    q(12, "Gosto de lugares e objetos que carregam história, tradição ou um toque clássico."),
    q(13, "Meu tempo livre é dedicado a atividades produtivas (aprender, organizar, planejar)."),
    q(14, "Sou controlado(a) com gastos, priorizando poupança e investimento."),
    q(15, "Preocupo-me em manter uma imagem séria e respeitável, especialmente no trabalho."),
    q(16, "Sinto-me bem usando cores neutras, escuras ou tradicionais (preto, cinza, marrom)."),
    q(17, "Prefiro sair para lugares sóbrios e tranquilos em vez de festas badaladas."),
    q(18, "Valorizo comida clássica, caseira ou que exija bom preparo e tradição."),
    q(19, "Gosto de lazer ao ar livre estruturado, como trilhas ou montanhismo."),
    q(20, "Prefiro um ritmo de vida mais lento, planejado e consistente."),
  ],

  // ♒ AQUÁRIO
  Aquarius: [
    q(1, "Minha liberdade pessoal é inegociável e resisto a qualquer tentativa de controle."),
    q(2, "Sou conhecido(a) por ter ideias originais, pouco convencionais e futuristas."),
    q(3, "Gosto de causas sociais e valorizo o bem-estar da comunidade acima do individual."),
    q(4, "Gosto de questionar o status quo e regras que não fazem sentido lógico."),
    q(5, "Tenho dificuldade com drama emocional; prefiro relações racionais e amigáveis."),
    q(6, "Minhas amizades são muito importantes e formam uma rede diversa."),
    q(7, "Sou tolerante e aceito pessoas e ideias muito diferentes das minhas."),
    q(8, "Posso ser visto(a) como frio(a) pois valorizo mais as ideias do que a expressão de sentimentos."),
    q(9, "Gosto de tecnologia, ciência, astrologia ou temas sobre o futuro."),
    q(10, "Mudo de planos ou foco com frequência; não suporto monotonia."),
    q(11, "Meu estilo é único e pessoal; visto-me para me expressar, não para a moda."),
    q(12, "Sinto atração por tudo que é novo, experimental ou de vanguarda."),
    q(13, "Gosto de atividades em grupo, clubes ou encontros com interesses comuns."),
    q(14, "Prefiro trabalhos com horários flexíveis que estimulem minha criatividade."),
    q(15, "Gosto de ambientes modernos, clean, minimalistas e funcionais."),
    q(16, "Gosto de cores elétricas ou vibrantes (azul-celeste, turquesa, metalizados)."),
    q(17, "Prefiro lugares onde possa conhecer gente nova e ter discussões intelectuais."),
    q(18, "Minha alimentação é despretensiosa e prática."),
    q(19, "Sou um dos primeiros a testar novos aplicativos e gadgets."),
    q(20, "Consigo me dar bem com pessoas de qualquer origem sem julgamentos."),
  ],

  // ♓ PEIXES
  Pisces: [
    q(1, "Absorvo as emoções das pessoas e ambientes, sendo profundamente empático(a)."),
    q(2, "Minha vida interior é rica e imagino cenários com frequência."),
    q(3, "Tenho impulso para ajudar quem precisa e me sacrifico pelos outros."),
    q(4, "Confio muito na minha intuição e pressentimentos."),
    q(5, "Às vezes uso arte, sono ou fantasia para escapar de problemas práticos."),
    q(6, "Tenho dificuldade em dizer 'não' ou impor limites."),
    q(7, "Minha vida pode ser um pouco caótica; planejamento rígido não é meu forte."),
    q(8, "Sou romântico(a) e idealizo pessoas, o que pode levar a decepções."),
    q(9, "Tenho interesse natural por temas místicos, espirituais ou meditação."),
    q(10, "Posso ser indeciso(a) e prefiro deixar as coisas acontecerem."),
    q(11, "Gosto de ambientes que estimulem a criatividade e a calma."),
    q(12, "Tenho forte atração por arte (música, poesia, foto) para expressar o que sinto."),
    q(13, "Valorizo a sensação de união e comunhão com as pessoas."),
    q(14, "O sono e os sonhos são essenciais para o meu bem-estar."),
    q(15, "Não dou muita importância a bens materiais; desapego fácil."),
    q(16, "Gosto de cores suaves e aquáticas (lilás, verde-água, tons pastel)."),
    q(17, "Prefiro saídas tranquilas, isoladas ou com música suave."),
    q(18, "Gosto de comidas leves ou que tragam conforto emocional."),
    q(19, "A música tem um poder imenso sobre meu humor."),
    q(20, "Gosto de fugir da rotina com viagens ou passeios perto da água."),
  ],

  // ♈ ÁRIES
  Aries: [
    q(1, "Sinto necessidade de ser o(a) primeiro(a) e assumo a liderança naturalmente."),
    q(2, "Sou corajoso(a) e ajo por impulso antes de pensar nas consequências."),
    q(3, "Gosto de competir e quero ser o(a) melhor ou vencedor(a)."),
    q(4, "Minha comunicação é direta, franca e honesta, às vezes brusca."),
    q(5, "Fico irritado(a) rápido, mas minha raiva passa rápido também."),
    q(6, "Sou orientado(a) para o presente; quero resultados imediatos."),
    q(7, "Sou independente e prefiro fazer as coisas do meu jeito."),
    q(8, "Tenho muita energia e preciso estar sempre em movimento."),
    q(9, "Tenho pouca paciência com lentidão ou burocracia."),
    q(10, "Sou movido(a) pela necessidade de superar desafios e provar meu valor."),
    q(11, "Adoro esportes ou atividades com adrenalina e desafio."),
    q(12, "Meu estilo é prático, atlético e focado no conforto."),
    q(13, "Sinto atração por ferramentas ou objetos que me permitam agir/consertar."),
    q(14, "Gosto de ser pioneiro(a) e estar no comando."),
    q(15, "Tenho facilidade em tomar decisões rápidas."),
    q(16, "Gosto de cores quentes e fortes (vermelho, laranja)."),
    q(17, "Para sair, prefiro lugares com energia, movimento ou dança."),
    q(18, "Gosto de comidas fortes, temperadas ou picantes."),
    q(19, "Tenho cicatrizes de atividades e isso não me incomoda."),
    q(20, "Foco mais nos meus objetivos do que nos dos outros."),
  ],

  // ♉ TOURO
  Taurus: [
    q(1, "Minha prioridade é ter segurança e estabilidade material e emocional."),
    q(2, "Sou paciente e persistente; avanço devagar até terminar."),
    q(3, "Tenho dificuldade em me desfazer de coisas/pessoas e posso ser possessivo(a)."),
    q(4, "O conforto físico e o prazer dos sentidos são muito importantes."),
    q(5, "Sou teimoso(a); decidido algo, difícil mudar de ideia."),
    q(6, "Sinto atração natural por natureza, jardins ou contato com a terra."),
    q(7, "Gosto de fazer as coisas no meu ritmo; odeio pressa."),
    q(8, "Trabalho duro e sei valorizar meus ganhos financeiros."),
    q(9, "Rotinas e hábitos estabelecidos me trazem paz."),
    q(10, "Tenho apreço pelo que é bonito, harmonioso e esteticamente agradável."),
    q(11, "Gosto de tirar o máximo proveito e conforto do que possuo."),
    q(12, "O toque e a qualidade tátil (roupas, cama) são essenciais."),
    q(13, "Tenho tendência a colecionar ou acumular bens."),
    q(14, "Sou bom(a) em planejar finanças a longo prazo."),
    q(15, "Prefiro o luxo simples e de alta qualidade a algo chamativo."),
    q(16, "Gosto de cores naturais e terrosas (verde, marrom, bege)."),
    q(17, "Saída ideal tem comida deliciosa, conforto e ambiente relaxante."),
    q(18, "Sou apreciador(a) da boa culinária e da fartura."),
    q(19, "Gosto de música que acalma e harmoniza."),
    q(20, "Prefiro passeios tranquilos (parques, fazendas)."),
  ],

  // ♊ GÊMEOS
  Gemini: [
    q(1, "Tenho facilidade em me expressar e adoro conversar sobre tudo."),
    q(2, "Tenho curiosidade insaciável; estou sempre aprendendo algo novo."),
    q(3, "Sou adaptável e consigo fazer várias tarefas ao mesmo tempo."),
    q(4, "Fico entediado(a) fácil com rotina e não fixo em um só projeto."),
    q(5, "Sinto ter várias facetas e meu humor muda rapidamente."),
    q(6, "Valorizo a quantidade de contatos e faço amizades facilmente."),
    q(7, "Gosto de jogos de palavras e meu raciocínio é rápido."),
    q(8, "Posso demonstrar interesse e perdê-lo subitamente."),
    q(9, "Prefiro analisar fatos racionalmente a me envolver emocionalmente."),
    q(10, "Gosto de pequenas viagens e explorar a vizinhança."),
    q(11, "Uso muito celular e redes sociais para estar informado(a)."),
    q(12, "Preciso de um ambiente de trabalho estimulante e livre."),
    q(13, "Prefiro roupas leves, joviais e que permitam movimento."),
    q(14, "Consumo muitas notícias e podcasts para me atualizar."),
    q(15, "Tenho habilidade manual (escrever, digitar, montar)."),
    q(16, "Gosto de cores claras e alegres (amarelo, azul-claro)."),
    q(17, "Gosto de lugares com gente, movimento e troca de ideias."),
    q(18, "Gosto de variedade na comida; não tenho prato fixo."),
    q(19, "Gosto mais do planejamento da viagem do que do destino."),
    q(20, "Uso humor e ironia frequentemente na comunicação."),
  ],

  // ♋ CÂNCER
  Cancer: [
    q(1, "Minhas decisões são guiadas por emoções e intuições."),
    q(2, "Tenho grande apreço pelo passado, lembranças e família."),
    q(3, "Gosto de cuidar e nutrir as pessoas de quem gosto."),
    q(4, "Minha família e meu lar são os pilares da minha vida."),
    q(5, "Sou sensível, me magoo fácil e reajo retraindo-me."),
    q(6, "Posso me tornar dependente emocionalmente de quem amo."),
    q(7, "Tenho memória excelente para detalhes emocionais."),
    q(8, "Tenho medo de perder quem amo; posso ser ciumento(a)."),
    q(9, "Meu humor é variável como as fases da Lua."),
    q(10, "Sinto forte pertencimento às minhas raízes."),
    q(11, "Adoro cozinhar e me sinto feliz no conforto do lar."),
    q(12, "Guardo objetos sentimentais e presentes."),
    q(13, "Minha casa é decorada para ser o mais aconchegante possível."),
    q(14, "Prefiro poucos relacionamentos, mas profundos e íntimos."),
    q(15, "Gosto de trabalhos que envolvam cuidar ou lidar com o passado."),
    q(16, "Gosto de cores suaves e lunares (prata, branco, tons pastéis)."),
    q(17, "Saída ideal é receber em casa ou lugares intimistas."),
    q(18, "Gosto de comida 'conforto' que remete à infância."),
    q(19, "Sinto atração por passeios perto da água."),
    q(20, "Tenho rituais ou sinto influência dos ciclos da natureza."),
  ],

  // ♌ LEÃO
  Leo: [
    q(1, "Gosto de ser notado(a) e estar no centro das atenções."),
    q(2, "Preciso me expressar e criar algo que reflita quem sou."),
    q(3, "Assumo a liderança naturalmente; gosto de ser a referência."),
    q(4, "Sou generoso(a) e trato as pessoas com dignidade."),
    q(5, "Meu orgulho é forte; detesto ser ignorado(a)."),
    q(6, "Tenho grande autoconfiança no meu valor."),
    q(7, "Às vezes exagero no drama para dar impacto."),
    q(8, "Sou extremamente leal e protetor(a) com os meus."),
    q(9, "Sinto-me estimulado(a) por elogios e reconhecimento."),
    q(10, "O amor-próprio é a base da minha vida."),
    q(11, "Aprecio marcas de qualidade, luxo e status."),
    q(12, "Gosto de entretenimento, seja assistindo ou atuando."),
    q(13, "Dedico-me a hobbies criativos (arte, teatro)."),
    q(14, "Sinto atração por posições de poder e influência."),
    q(15, "Cuido muito da minha aparência e cabelo."),
    q(16, "Gosto de cores quentes e nobres (dourado, amarelo, vermelho)."),
    q(17, "Gosto de lugares elegantes onde possa ver e ser visto(a)."),
    q(18, "Gosto de comidas ricas e bem apresentadas."),
    q(19, "Gosto de lazer luxuoso ou espetáculos."),
    q(20, "Gosto de sentir que as pessoas me admiram."),
  ],

  // ♍ VIRGEM
  Virgo: [
    q(1, "Tenho olhar atento aos detalhes e analiso tudo minuciosamente."),
    q(2, "Minha produtividade depende de ordem e organização."),
    q(3, "Sinto-me bem sendo útil e resolvendo problemas práticos."),
    q(4, "Sou perfeccionista; incomoda-me o que está malfeito."),
    q(5, "Sou muito crítico(a) comigo mesmo(a)."),
    q(6, "Preocupo-me muito com saúde, alimentação e higiene."),
    q(7, "Sou pragmático(a); valorizo soluções concretas."),
    q(8, "Preocupo-me em me expressar com precisão."),
    q(9, "Prefiro a discrição; não gosto de expor minha vida."),
    q(10, "Fico ansioso(a) se sinto que algo foge do controle."),
    q(11, "Faço listas e gosto de ter o dia planejado."),
    q(12, "Valorizo economia e detesto desperdício."),
    q(13, "Gosto de aprender habilidades com aplicação prática."),
    q(14, "Meu ambiente precisa estar limpo para eu me concentrar."),
    q(15, "Meu estilo é clássico, discreto e impecável."),
    q(16, "Gosto de cores neutras e clean (bege, branco, verde-escuro)."),
    q(17, "Prefiro lugares tranquilos que ofereçam aprendizado."),
    q(18, "Prefiro comida natural, saudável e de origem conhecida."),
    q(19, "Aprecio rotinas que trazem previsibilidade."),
    q(20, "Prefiro ajudar nos bastidores sem precisar de confetes."),
  ],

  // ♎ LIBRA
  Libra: [
    q(1, "Detesto conflito e faço tudo para manter a paz."),
    q(2, "Sinto-me melhor em parceria ou relacionamento."),
    q(3, "Tenho dificuldade em decidir, pois vejo todos os lados."),
    q(4, "Tenho forte senso de justiça e busco imparcialidade."),
    q(5, "Sou diplomático(a) e me dou bem com quase todos."),
    q(6, "Preocupo-me com a opinião dos outros e em ser agradável."),
    q(7, "A beleza e a estética são essenciais; não suporto feiura."),
    q(8, "Sou habilidoso(a) em mediar conflitos."),
    q(9, "Gosto de companhia e não gosto de ficar só."),
    q(10, "Posso mudar de ideia para agradar o grupo."),
    q(11, "Gosto de moda e tenho bom gosto."),
    q(12, "Gosto de decorar para deixar o ambiente harmonioso."),
    q(13, "Busco equilibrar todas as áreas da vida."),
    q(14, "Sinto atração por arte e cultura."),
    q(15, "Gosto de sair em casal e ser visto(a) socialmente."),
    q(16, "Gosto de cores suaves e elegantes (rosa, azul, tons pastéis)."),
    q(17, "Gosto de lugares sofisticados, bonitos e sociáveis."),
    q(18, "Prefiro comidas delicadas e bem apresentadas."),
    q(19, "Gosto de passeios românticos e culturais."),
    q(20, "Gosto de soluções que simplificam a vida."),
  ],

  // ♏ ESCORPIÃO
  Scorpio: [
    q(1, "Vivo as emoções de forma extrema e intensa."),
    q(2, "Sou reservado(a) e atraído(a) por mistérios."),
    q(3, "Preciso sentir que tenho controle sobre mim e o ambiente."),
    q(4, "Minha vida tem constantes transformações e renascimentos."),
    q(5, "Sou extremamente leal, mas implacável com traição."),
    q(6, "Tenho intuição profunda, quase um raio-X das pessoas."),
    q(7, "Tenho facilidade em guardar rancor se for magoado(a)."),
    q(8, "Busco profundidade; odeio superficialidade."),
    q(9, "Luto contra tendências a ciúmes e possessividade."),
    q(10, "Tenho impulso natural para investigar e ir fundo."),
    q(11, "Atraem-me temas como psicologia, ocultismo e tabus."),
    q(12, "Valorizo conexões íntimas de fusão emocional."),
    q(13, "Sinto atração por risco e situações limite."),
    q(14, "Quando corto algo da vida, é definitivo."),
    q(15, "Gosto do silêncio e da solitude para regenerar."),
    q(16, "Gosto de cores intensas e escuras (preto, vinho, roxo)."),
    q(17, "Prefiro lugares discretos, íntimos e com pouca luz."),
    q(18, "Gosto de sabores fortes e intensos."),
    q(19, "Aprecio música dramática ou profunda."),
    q(20, "Sou bom(a) em gerenciar recursos compartilhados."),
  ],

  // ♐ SAGITÁRIO
  Sagittarius: [
    q(1, "Tenho fé inabalável de que as coisas darão certo."),
    q(2, "Amo viajar e preciso de liberdade para explorar."),
    q(3, "Sou muito sincero(a), às vezes até demais."),
    q(4, "Gosto de estudar filosofia e o sentido da vida."),
    q(5, "Tenho tendência a exagerar (nos gastos, emoções)."),
    q(6, "Sou conhecido(a) pelo bom humor e alegria."),
    q(7, "Tenho código moral forte e gosto de ensinar."),
    q(8, "Tenho energia que me impede de ficar parado(a)."),
    q(9, "Minhas metas são sempre grandes e ousadas."),
    q(10, "Tenho círculo social amplo e gosto de estrangeiros."),
    q(11, "Gosto de esportes ao ar livre e espaços amplos."),
    q(12, "Meu estilo é despojado e confortável para aventuras."),
    q(13, "Gosto de ler livros longos e profundos."),
    q(14, "Sinto atração por animais de grande porte."),
    q(15, "Sinto satisfação em ser mentor(a)."),
    q(16, "Gosto de cores de realeza e vastidão (azul-marinho, roxo)."),
    q(17, "Gosto de lugares amplos, festivos e internacionais."),
    q(18, "Gosto de comidas exóticas de outras culturas."),
    q(19, "Prefiro viagens longas para destinos distantes."),
    q(20, "Valorizo mais a honestidade do que o status."),
  ],
};